### ISSUE TITLE
Base64 to base64url

### ISSUE THREAD

**Issue by Villux** [mikeflynn/gmail-clj#2]
Gmail won't accept base64 encoding if it's not url safe. Would it be possible to use base64url?

**Comment by mikeflynn** [comment]
I just pushed a change to a b64url branch, but I'm unable to test it at the moment. If you have a chance, you can check that branch and see if it fixes your problem but I should be able to test it later today or tomorrow.

**Comment by mikeflynn** [comment]
My basic testing looks fine with this as my base64 url replacements conforms to the standards.

```
(defn str->b64 [input]
  (let [input (if (bytes? input) input (.getBytes input))]
    (-> (String. (b64/encode input) "UTF-8")
        (clojure.string/replace "\\+" "-")
        (clojure.string/replace "/" "_"))))
```

I'm going to merge this in an increment the version number.

**Comment by Villux** [comment]
Thanks for the quick fix!

**Comment by mikeflynn** [comment]
No problem. Let me know if that's still not working for you.

**Comment by Villux** [comment]
Just had time to test this, but it won't work. I'm afraid that for some reason Leiningen wont update the dependency. It should be under version 0.6.3?

**Comment by mikeflynn** [comment]
Hmm, are you saying that Leinigen isn't pulling down the latest release from Clojars (https://clojars.org/gmail-clj) or that it is but the change isn't working?

**Comment by Villux** [comment]
Hmm. I'm not that familiar with Leiningen, but after I removed all version from 0.6.1 to 0.6.3 it started to work. I had 0.6.3 in my project file, but still it used the old one. Code works, so thanks a lot!
