### ISSUE TITLE
Why not do the POST and retrieve the refresh token?

### ISSUE THREAD

**Issue by klauswuestefeld** [mikeflynn/gmail-clj#5]
It would have saved me several hours hacking and studying OAuth docs.
https://github.com/mikeflynn/gmail-clj/blob/70b3fef5ef3518cc2623b22adc75c33ab89cb86b/resources/index.html#L55

**Comment by mikeflynn** [comment]
It did actually do that originally (you can see the commented out portion below the the line you called out), but it's been a while and can't remember why we pivoted.

If you want to submit a pull request there's no reason to revisit the issue.

**Comment by klauswuestefeld** [comment]
I don't know JS enough to do that. :/

**Comment by klauswuestefeld** [comment]
Expired
